# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycut < Formula
  desc "Terminal-based video trimming TUI (ffmpeg + chafa)"
  homepage "https://github.com/emin-ozata/lazycut"
  version "0.1.3"

  depends_on "chafa"
  depends_on "ffmpeg"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.1.3/lazycut_0.1.3_darwin_amd64.tar.gz"
    sha256 "164443b571c866f451be1708de3a0d1575919db7cc47656f2617be1584032e0b"

    def install
      bin.install "lazycut"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.1.3/lazycut_0.1.3_darwin_arm64.tar.gz"
    sha256 "94964cc6bba8d3d22504cf65191e4437882f010bc31bd176d030b094c3663623"

    def install
      bin.install "lazycut"
    end
  end

  test do
    output = shell_output("#{bin}/lazycut 2>&1", 1)
    assert_match "Usage: lazycut", output
  end
end
