# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycut < Formula
  desc "Terminal-based video trimming TUI (ffmpeg + chafa)"
  homepage "https://github.com/emin-ozata/lazycut"
  version "0.3.0"

  depends_on "chafa"
  depends_on "ffmpeg"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.0/lazycut_0.3.0_darwin_amd64.tar.gz"
    sha256 "b89fd411e81ff2b133896e47a0400d9276e01aba754b05d78e3d955beee0c804"

    def install
      bin.install "lazycut"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.0/lazycut_0.3.0_darwin_arm64.tar.gz"
    sha256 "e98c9826919a7fada6ee863256d4d4131724588c509ebf60887d9dc41474d360"

    def install
      bin.install "lazycut"
    end
  end

  test do
    output = shell_output("#{bin}/lazycut 2>&1", 1)
    assert_match "Usage: lazycut", output
  end
end
