# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycut < Formula
  desc "Terminal-based video trimming TUI (ffmpeg + chafa)"
  homepage "https://github.com/emin-ozata/lazycut"
  version "0.3.2"

  depends_on "chafa"
  depends_on "ffmpeg"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.2/lazycut_0.3.2_darwin_amd64.tar.gz"
    sha256 "aa684c95ba4ac4daffa399fd1e23403d0c48bd17e4996fcf97479ee5028a80db"

    def install
      bin.install "lazycut"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.2/lazycut_0.3.2_darwin_arm64.tar.gz"
    sha256 "3e74fd1ddcc6f3374deffb4fdecf649eafcdd19547825590a0e13f3f08968eea"

    def install
      bin.install "lazycut"
    end
  end

  test do
    output = shell_output("#{bin}/lazycut 2>&1", 1)
    assert_match "Usage: lazycut", output
  end
end
